# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7ba029a240ca80dc4aa51f257ad14c03af873f19877637b87e2e5df18d29a6e05aae474db87d69d61ae21378e0980ff58343a3c7d75db867c8fdc10fabff808

test:
  secret_key_base: a5049b4f0a21e7076c304a57d98cdfa288c3957b876947548ff70f789ea1a2785277c0ee1a53cb94796722a9c32b4f6df8a40f38e323d68b9fcffe7f43d4aad0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
